### PR TITLE
Use a Python virtual environment in the Docker image

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request updates the image configuration to use a Python virtual environment instead of the system Python environment to install Ansible and other required packages.

## 💭 Motivation and context ##

Debian 12 (Bookworm) is now configuring its Python base environment as "externally managed" per [PEP 668](https://peps.python.org/pep-0668/). As a result you can only install system Python packages from apt packages. Any non-apt Python packages must be installed using a Python virtual environment.

## 🧪 Testing ##

Mirroring what is done in the [GitHub Actions workflow](https://github.com/cisagov/docker-debian12-ansible/blob/654cf8700563d9fdf5f2453991d38a3302ba2433/.github/workflows/build.yml#L21-L28) I verified that I could:
1. Build the image successfully.
2. Start the image successfully.
3. Get the version of Ansible from the running container.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
I like these changes, but I'm not keen on treating Debian 12 differently than other platforms.  I wish we could do this for _all_ platforms.  As it stands, we will have to remember to pop into the virtual environment when using - and only when using - Debian 12.

Tagging @geerlingguy since this will eventually be something that he has to deal with too.

**Comment by geerlingguy** [comment]
That's kind of unfortunate... I avoid using venvs whenever possible because I favor simplicity :P

**Review by dav3r — APPROVED** [review]

**Comment by mcdonnnj** [comment]
> I like these changes, but I'm not keen on treating Debian 12 differently than other platforms. I wish we could do this for _all_ platforms. As it stands, we will have to remember to pop into the virtual environment when using - and only when using - Debian 12.
> 
> Tagging @geerlingguy since this will eventually be something that he has to deal with too.

Would you clarify what do you mean by:
> As it stands, we will have to remember to pop into the virtual environment when using - and only when using - Debian 12.

**Comment by jsf9k** [comment]
> Would you clarify what you mean by:
> 
> > As it stands, we will have to remember to pop into the virtual environment when using - and only when using - Debian 12.

Yes, that was inexcusably unclear.  If someone were to create a new Docker image that uses this one as a base image, and a similar one from `geerlingguy/docker-debian11-ansible`, then that person would have to keep in mind that `geerlingguy/docker-debian11-ansible` does not use a venv while `geerlingguy/docker-debian12-ansible` does.  I'm just saying that it would be nice if these Docker images were built similarly across the board.

**Comment by mcdonnnj** [comment]
> > Would you clarify what you mean by:
> > > As it stands, we will have to remember to pop into the virtual environment when using - and only when using - Debian 12.
> 
> Yes, that was inexcusably unclear. If someone were to create a new Docker image that uses this one as a base image, and a similar one from `geerlingguy/docker-debian11-ansible`, then that person would have to keep in mind that `geerlingguy/docker-debian11-ansible` does not use a venv while `geerlingguy/docker-debian12-ansible` does. I'm just saying that it would be nice if these Docker images were built similarly across the board.

Ahh ok. That makes a lot more sense. Thanks for the clarification.

**Comment by mcdonnnj** [comment]
This was superseded by #5.

**Pull request closed without merging**
